### ISSUE TITLE
Notification and Invite | Proposal

### ISSUE THREAD

**Issue by TFWIsaac** [MorpheusXAUT/slotlist-frontend#107]
Here two proposals,

first an Invite-menu, that a person (mission creator or editor) could invite other persons or complete communitys.
That requires an notificationmenu, where an invite could be displayed, or if someone gets editor permissions at a mission, or his application was accepted.

**Comment by MorpheusXAUT** [comment]
Some sort of notification system has been very roughly planned, but there's currently no exact plans on how to implement it or an exact release date yet.
The notifications could only be restricted to the site itself as well since we do not store any ways to contact the user or send a push notification or likewise.

@TFWIsaac what exactly would you like to use those invites for? Or in other words: how would they differ from reserving slots for a community?
Or would those invites simply send out notifications to the users/communities as well?

**Comment by TFWIsaac** [comment]
first a thougt thats a simple notification for users/communities, that they know they can participate at missions.

**Comment by MorpheusXAUT** [comment]
Hmm, alright... I'll have to find time to build a notification system first, so no ETA for this yet unfortunately.

**Comment by MorpheusXAUT** [comment]
@TFWIsaac I'm currently implementing a notification list. Would you rather have all automatically notification marked as "seen" once they have been loaded once, or have to mark them as "seen" manually?
There's an "unseen notification" count at the top of the page, which leads you to the list of notifications.
Seen notifications can be shown via a checkbox, similar to past missions.

Automatically marking them as seen is faster/less clicks, but you potentially don't see some if you click too fast.
Manually marking them makes sure you've seen them, but requires the user to click.

**Comment by MorpheusXAUT** [comment]
Closed as completed in accordance with Isaac.
Actual invitations within the site do not provide any great benefit at the moment - the rest of the suggestion has been implemented.
