### ISSUE TITLE
Proposal | Add a auto-accept mode for slot registrations.

### ISSUE THREAD

**Issue by Bnarington** [MorpheusXAUT/slotlist-frontend#125]
A way for users to assign themselves to slots, removing the need for mission makers to accept registrations.

-[JTF16] Bnar

**Comment by MorpheusXAUT** [comment]
Valid suggestions, should be relatively easy to implement as well.
I'll definitely keep it in mind, but am currently a bit behind on development due to other responsibilites.

**Comment by MorpheusXAUT** [comment]
@Bnarington will be added with the next release, hopefully sometime this weekend or start of next week. I still have some other mod-repository stuff to add, but it's mostly done, so should be ready shortly.

**Comment by Bnarington** [comment]
Awesome! thanks 👍

**Comment by MorpheusXAUT** [comment]
@Bnarington done and deployed 😄 hope that was what you had in mind

**Comment by Bnarington** [comment]
Awesome! exactly what I was looking for, thanks a bunch!

**Comment by Bnarington** [comment]
After checking it out and testing it, is it possible to make it so I can set the mission as auto assignable? So I don't have to go into every slot on a slotlist and change it.

**Comment by MorpheusXAUT** [comment]
You could currently change it for multiple slots at the same time by `CTRL + Click`ing them and then editing the setting for all at once, but I can see the usefulness of having it on "mission-basis" as well.
I'll definitely keep the setting on each of the slots, but will add another one on the mission that basically automatically enables it for every existing/new slot.

**Comment by MorpheusXAUT** [comment]
@Bnarington with the auto-assignable setting for the mission, which implementation would you prefer:

1. Enabling the `auto-assignable` setting for a mission sets the `auto-assignable` setting for ever slot **created after** the mission-setting was enabled
2. Enabling the `auto-assignable` setting for a mission automatically accepts all registrations for that mission, no matter what the individual setting for each slot is or when these slots were created

Solution 1) would provide more fine-grained control, but potentially requires more clicking when you enable the setting after creating slots, while solution 2) is "broader", but only requires a single click.

**Comment by Bnarington** [comment]
I think solution 1 is the best way to go. At that point if I understand correctly I can create slot groups that I want to be register only first, and then hit the button to make auto-assign happen, make a bunch of other slots and only those that is made after the auto-assign button is hit is made self-assignable? (what a sentance :|)

**Comment by MorpheusXAUT** [comment]
Yup, exactly. The way solution 1 would work is basically like you described:

Before you set the missions auto-assign setting to "on", every slot requires confirmation (or whatever setting you choose for that particular slot). That means you could first create a group of slots you want to require confirmations for.

All slots created **after** the setting has been turned "on" would basically have their respective setting "overwritten" to always be enabled. That means every slot you create after setting the mission setting to "on" would automatically be auto-assignable.

If you wanted, you could afterwards edit certain slots and disable the auto-assignment for them, but that's a different part.

I also prefer solution 1 because it gives you more control about your slotlist, but still provides the "comfort" of not having to tick the checkbox on each slot.

**Comment by Bnarington** [comment]
Awesome, that sounds like a really good solution to it!

**Comment by MorpheusXAUT** [comment]
Done, will be added with the next deployment.
The way it's build now:

- Enabling the mission's auto-assignable setting automatically enables the auto-assignable setting for all slots **created from this point on**. All existing slots are unaffected.
- Even with the mission's auto-assignable setting enabled, you can still edit single slots and update their setting (allowing you to create a full slotlist and just disable it for a few slots afterwards).
- Duplicating a slot (or slotgroup, since that basically duplicates all slots separately) respects the slot's auto-assignable setting, but does not enforce the mission's one. Thus, if you duplicate a slot/slotgroup that is not auto-assignable, the duplicated slot will require a mission editor's confirmation as well.

I'd say that should fit your request the best - let me know if you prefer any other changes.
