### ISSUE TITLE
When copying groups of slots only the title is copied. 

### ISSUE THREAD

**Issue by Bnarington** [MorpheusXAUT/slotlist-frontend#130]
When I copy a slotgroup on the title is copied and the slots in the group. I think it might have to do with the auto accept option, as when trying to copy a slot with autoaccept on the site gives and error. 

>  Failed to create slot - "value" at position 0 fails because [child "autoAssignable" fails because ["autoAssignable" is required]]

This error is not given when copying the group tho.

**Comment by MorpheusXAUT** [comment]
Welp, god damn, I knew I forgot something when I added the auto-assignment option.
Yup, definitely due to the single slots not being able to be created - the group copy action just "swallows" the single-slot errors so failing to create one slot doesn't stop the whole duplication process. In this case, every single one of them fails though, so, yeah...

Will definitely fix that ASAP, thanks for the find!

I should definitely add unit tests to the backend to catch stuff like that... 🙄
