### ISSUE TITLE
Add Creator DLC: GM to required DLC

### ISSUE THREAD

**Issue by Kili-97** [MorpheusXAUT/slotlist-frontend#138]
Add Creator DLC: GM to required DLC

![2019-05-06_18-35-50](https://user-images.githubusercontent.com/42013222/57240020-d6237d00-702d-11e9-9797-6b7d9be3eb12.png)

**Comment by Scarjit** [comment]
Adding to that:
Please add Arma3 - Contact to the list of required DLC's

**Comment by MorpheusXAUT** [comment]
Hi,

sorry for the super delayed response @IDarky and @Scarjit, unfortunately I haven't been active in the ArmA scene for quite a few years and didn't find the time to maintain the project in my free time.

The icon's I've used for the existing required DLCs are part of an ArmA3 "font" used by BI on their homepage - unfortunately the font does not contain any pictograms except the ones currently included (and seen on the screenshot above). Since I did not have the time (and skills) to create my own icons, I did not add the other (creator) DLCs so far.

I could probably add them without an icon with light to moderate work needed though, given I can still successfully create a local build of this project 😅
I'll see if I can find the time to try and add them during this week (or weekend).

If someone _does_ have proper icons for the DLCs missing, please let me know.

**Comment by MorpheusXAUT** [comment]
Just released an update with the current list of DLCs included.
