### ISSUE TITLE
Can´t connect via Steam, error occurs

### ISSUE THREAD

**Issue by DasBoehse** [MorpheusXAUT/slotlist-frontend#139]
Hey,

i fill in my Steam name an password, also the authenticator code. After that an error occurs every time.

"Login went wrong, somethimg failed." Am i doing something wrong?

Thank you verry much in advance.

Best regards
Jan

**Comment by b-mayr-1984** [comment]
Hi,
You might try this as a workaround. 

1. Change your Steam nickname temporarily to something else.
2. Try again to log in to Slotlist.info using SteamID.
3. If it still fails try another nickname that you can be certain of, that it has not yet been used on Slotlist.info .

This should do the trick until this problem is fixed. :-)

**Comment by MorpheusXAUT** [comment]
Hi,

sorry for the huge delay @DasBoehse, unfortunately I haven't been active in the ArmA scene in quite a few years and did not find the time to keep working on the project in my free time.

As @b-mayr-1984 has noted, this was potentially caused by the "nickname" column only allowing one user to have a certain nickname, if two people e.g. called "Jan" would try to log in, only the first one would be able to do so.

I have now removed the restrictions (which I honestly don't remember why it was present in the first place), you should hopefully be able to log in without any issues now, if this is still relevant to you or you didn't find a way around the issue in the meantime.

Please let me know if you encounter any other issues after login, sorry again for the huge delay.

**Comment by MorpheusXAUT** [comment]
Closed for now as a different test in #140 was successful. Please re-open the issue or create a new one should you encounter any problems after the change.
