### ISSUE TITLE
Uploading pictures and deleting missions leads to "An internal server error occurred"

### ISSUE THREAD

**Issue by Pyro456** [MorpheusXAUT/slotlist-frontend#152]
Since last week, I've been unable to use a few editing options. Every time the website returns an internal server error. This happens when I upload/delete the banner or if I want to delete the mission. The problem occurs also to others in my community.
[Picture](https://i.imgur.com/nH3Uem0.jpg)

**Comment by MorpheusXAUT** [comment]
Hi @Pyro456,

thanks for the heads up.

I've recently moved to a different server host in order to cut costs a bit. Looks like the storage access for image uploads is not working properly anymore after the move.
I'll try to take a look and fix it in the next few days. Feel free to poke me again on Sunday should I have forgotten until then 😅

**Comment by Pyro456** [comment]
@MorpheusXAUT the reminder you asked for ;)

**Comment by MorpheusXAUT** [comment]
@Pyro456 thanks for the reminder, sorry it took so long.
Should be fixed now, test upload as a banner image and to the mission description worked for me. Could you verify it's working for you as well?

**Comment by Pyro456** [comment]
Works again. Thank you!
