### ISSUE TITLE
Missing Mission description at the community details

### ISSUE THREAD

**Issue by TFWIsaac** [MorpheusXAUT/slotlist-frontend#71]
At the community details page (https://slotlist.info/communities/[...]), in the mission part, the description is missing from the community mission.

**Comment by MorpheusXAUT** [comment]
Found the issue - since I've removed the mission description from the mission list (https://slotlist.info/missions), I've also dropped the description from the API response.
Buur mentioned that describing a mission in one short sentence is hardly ever possible, so I've decided to drop this piece of information.
I'll remove it from the community and user mission lists as well...
